# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrashRecordServiceStub(object):
    """Service to manage crash records
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCrashRecord = channel.unary_unary(
                '/crashrecord.CrashRecordService/CreateCrashRecord',
                request_serializer=data__pb2.CreateCrashRecordRequest.SerializeToString,
                response_deserializer=data__pb2.CreateCrashRecordResponse.FromString,
                _registered_method=True)
        self.GetCrashRecord = channel.unary_unary(
                '/crashrecord.CrashRecordService/GetCrashRecord',
                request_serializer=data__pb2.GetCrashRecordRequest.SerializeToString,
                response_deserializer=data__pb2.GetCrashRecordResponse.FromString,
                _registered_method=True)
        self.ListCrashRecords = channel.unary_unary(
                '/crashrecord.CrashRecordService/ListCrashRecords',
                request_serializer=data__pb2.ListCrashRecordsRequest.SerializeToString,
                response_deserializer=data__pb2.ListCrashRecordsResponse.FromString,
                _registered_method=True)
        self.DeleteCrashRecord = channel.unary_unary(
                '/crashrecord.CrashRecordService/DeleteCrashRecord',
                request_serializer=data__pb2.DeleteCrashRecordRequest.SerializeToString,
                response_deserializer=data__pb2.DeleteCrashRecordResponse.FromString,
                _registered_method=True)


class CrashRecordServiceServicer(object):
    """Service to manage crash records
    """

    def CreateCrashRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrashRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCrashRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCrashRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrashRecordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCrashRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCrashRecord,
                    request_deserializer=data__pb2.CreateCrashRecordRequest.FromString,
                    response_serializer=data__pb2.CreateCrashRecordResponse.SerializeToString,
            ),
            'GetCrashRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrashRecord,
                    request_deserializer=data__pb2.GetCrashRecordRequest.FromString,
                    response_serializer=data__pb2.GetCrashRecordResponse.SerializeToString,
            ),
            'ListCrashRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCrashRecords,
                    request_deserializer=data__pb2.ListCrashRecordsRequest.FromString,
                    response_serializer=data__pb2.ListCrashRecordsResponse.SerializeToString,
            ),
            'DeleteCrashRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCrashRecord,
                    request_deserializer=data__pb2.DeleteCrashRecordRequest.FromString,
                    response_serializer=data__pb2.DeleteCrashRecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crashrecord.CrashRecordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crashrecord.CrashRecordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrashRecordService(object):
    """Service to manage crash records
    """

    @staticmethod
    def CreateCrashRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashrecord.CrashRecordService/CreateCrashRecord',
            data__pb2.CreateCrashRecordRequest.SerializeToString,
            data__pb2.CreateCrashRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrashRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashrecord.CrashRecordService/GetCrashRecord',
            data__pb2.GetCrashRecordRequest.SerializeToString,
            data__pb2.GetCrashRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCrashRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashrecord.CrashRecordService/ListCrashRecords',
            data__pb2.ListCrashRecordsRequest.SerializeToString,
            data__pb2.ListCrashRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCrashRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashrecord.CrashRecordService/DeleteCrashRecord',
            data__pb2.DeleteCrashRecordRequest.SerializeToString,
            data__pb2.DeleteCrashRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
